
nach0.recipes.lockRecipeBehindTechnology("kr-basic-fluid-handling", "bi-wood-pipe")
nach0.recipes.lockRecipeBehindTechnology("kr-basic-fluid-handling", "bi-wood-pipe-to-ground")
nach0.recipes.lockRecipeBehindTechnology("kr-steam-engine", "steam-inserter")
nach0.recipes.lockRecipeBehindTechnology("kr-steam-engine", "steam-mining-drill")
nach0.recipes.disable("geothermal-heat-exchanger")
nach0.recipes.disable("geothermal-well")
nach0.recipes.lockRecipeBehindTechnology("kr-automation-core", "burner-assembling-machine")
nach0.recipes.disable("solder")
nach0.recipes.lockRecipeBehindTechnology("electronics", "bob-rubber")
nach0.recipes.disable("napalm-rocket")
nach0.recipes.disable("explosive-rocket-conversion-to-napalm-rocket")
nach0.recipes.disable("napalm-shell")
nach0.recipes.disable("neutron-rocket")
nach0.recipes.disable("neutron-shell")
nach0.recipes.lockRecipeBehindTechnology("solar-energy-3", "5d-gold-wire")
nach0.recipes.lockRecipeBehindTechnology("dirty-mining", "twig-to-wood")
nach0.recipes.lockRecipeBehindTechnology("dirty-mining", "pebbles-to-stone")
nach0.recipes.lockRecipeBehindTechnology("advanced-electronics", "stone-tablet")
nach0.recipes.lockRecipeBehindTechnology("logistics", "5d-tin-gear-wheel")
nach0.recipes.disable("5d-aluminium-gear-wheel")
nach0.recipes.lockRecipeBehindTechnology("advanced-electronics-2", "5d-gold-plate")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing", "5d-zinc-plate")
nach0.recipes.lockRecipeBehindTechnology("kr-stone-processing", "tin-plate")

nach0.recipes.lockRecipeBehindTechnology("5d-masher-1", "5d-iron-dust")
nach0.recipes.lockRecipeBehindTechnology("5d-masher-1", "5d-copper-dust")
nach0.recipes.lockRecipeBehindTechnology("5d-masher-1", "5d-tin-dust")
nach0.recipes.lockRecipeBehindTechnology("5d-masher-1", "5d-lead-dust")
nach0.recipes.lockRecipeBehindTechnology("5d-masher-1", "tungsten-dust")
nach0.recipes.lockRecipeBehindTechnology("5d-masher-1", "5d-zinc-dust")
nach0.recipes.lockRecipeBehindTechnology("5d-masher-1", "5d-aluminium-dust")
nach0.recipes.lockRecipeBehindTechnology("5d-masher-1", "5d-gold-dust")
nach0.recipes.lockRecipeBehindTechnology("5d-masher-1", "5d-iron-plate")
nach0.recipes.lockRecipeBehindTechnology("5d-masher-1", "5d-copper-plate")
nach0.recipes.lockRecipeBehindTechnology("5d-masher-1", "tin-plate-2")
nach0.recipes.lockRecipeBehindTechnology("5d-masher-1", "lead-plate-dust")
nach0.recipes.lockRecipeBehindTechnology("5d-masher-1", "tungsten-plate-dust")
nach0.recipes.lockRecipeBehindTechnology("5d-masher-1", "5d-zinc-plate-2")
nach0.recipes.lockRecipeBehindTechnology("5d-masher-1", "5d-aluminium-plate-2")
nach0.recipes.lockRecipeBehindTechnology("5d-masher-1", "5d-gold-plate-2")

nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "5d-iron-plate-industrial")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "5d-copper-plate-industrial")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "5d-tin-plate-industrial")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "lead-plate-industrial-ore")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "tungsten-plate-industrial-ore")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "5d-zinc-plate-industrial")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "5d-aluminium-plate-industrial")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "5d-gold-plate-industrial")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "5d-steel-plate-industrial")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "5d-iron-plate-industrial-dust")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "5d-copper-plate-industrial-dust")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "5d-tin-plate-industrial-dust")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "lead-plate-industrial-dust")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "tungsten-plate-industrial-dust")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "5d-zinc-plate-industrial-dust")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "5d-aluminium-plate-industrial-dust")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "5d-gold-plate-industrial-dust")
nach0.recipes.lockRecipeBehindTechnology("advanced-material-processing-12", "5d-zinc-gear-wheel")